# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:13:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Result(BaseModel):
    currency_code: Optional[str] = Field(
        None, description='The currency that the price is in'
    )
    description: Optional[str] = Field(
        None, description='The description of the product'
    )
    price: Optional[float] = Field(None, description='The price of the product')
    title: Optional[str] = Field(None, description='The title of the product')
    url: Optional[str] = Field(
        None, description='The url of the product page for this product'
    )


class SearchResponse(BaseModel):
    results: Optional[List[Result]] = None
